name: banp
description: Creates new project on Bitrise.io using a local bitrise.yml or running the Bitrise scanner.
executable:
  osx: https://github.com/bitrise-io/bitrise-add-new-project/releases/download/0.4.0/banp-Darwin-x86_64
  linux: https://github.com/bitrise-io/bitrise-add-new-project/releases/download/0.4.0/banp-Linux-x86_64
trigger: ""
requirements:
- tool: bitrise
  min_version: 1.3.0
  max_version: ""